name: Build Singularity
on: 
  # Manually run workflow
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the built container"
        required: true
        default: "dev"

  # Trigger on push  
  push:

    # This recipe shows how to manually define a matrix of singularity recipes (paths) to build
    # Edit the branches here if you want to change deploy behavior
    branches:
      - main
      - master

  # Trigger on PR
  pull_request: []

  # Trigger on published release
  release:
    types: [published]

# Set path to definition file
env:
  DEF_PATH: Singularity

jobs:
  check-file-existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File Existence
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: ${{ env.DEF_PATH }}
          allow_failure: true

  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.save-output.outputs.tag }}
    steps:
      - name: Manually Triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag=${{ github.event.inputs.tag }}
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Triggered by Release
        if: github.event_name == 'release'
        run: |
          tag=${{ github.ref }}
          tag=${tag##*/}
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Triggered by Push or PR
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          tag=dev 
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Save output
        id: save-output
        run: |
          echo "::set-output name=tag::${{ env.TAG }}"
          echo "Tag is ${{ env.TAG }}"

  build-container:
    needs: [check-file-existence, generate-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.6.4

      - name: Build Container
        run: |
          singularity build container.sif ${{ env.DEF_PATH }}

      - name: Archive built container
        uses: actions/upload-artifact@v2
        with:
          name: container
          path: container.sif

      - name: Login and deploy container
        if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${{ needs.generate-tag.outputs.tag }}

  # deploy-container:
  #   needs: [check-file-existence, generate-tag, build-container]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download a single artifact
  #       if: github.event_name != 'pull_request'
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: container
