name: Build Singularity
on:
  # Manually run workflow
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the built container"
        required: true
        default: "dev"

  # # Trigger on push
  # push:

  #   # This recipe shows how to manually define a matrix of singularity recipes (paths) to build
  #   # Edit the branches here if you want to change deploy behavior
  #   branches:
  #     - main
  #     - master

  # # Trigger on PR
  # pull_request: []

  # # Trigger on published release
  # release:
  #   types: [published]

# Set path to definition file
env:
  DEF_PATH: Singularity

jobs:
  check-file-existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: File Existence
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: ${{ env.DEF_PATH }}
          allow_failure: true

  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.save-output.outputs.tag }}
    steps:
      - name: Manually Triggered
        if: github.event_name == 'workflow_dispatch'
        run: |
          tag=${{ github.event.inputs.tag }}
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Triggered by Release
        if: github.event_name == 'release'
        run: |
          tag=${{ github.ref }}
          tag=${tag##*/}
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Triggered by Push or PR
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          tag=dev
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Save output
        id: save-output
        run: |
          echo "::set-output name=tag::${{ env.TAG }}"
          echo "Tag is ${{ env.TAG }}"

  build-container:
    needs: [check-file-existence, generate-tag]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Cache Go
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config

      - name: Install Singularity
        env:
          SINGULARITY_VERSION: 3.8.3
          GOPATH: /tmp/go
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt && \
          mkdir -p $GOPATH/src/github.com/sylabs && \
          cd $GOPATH/src/github.com/sylabs && \
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | \
          tar xzv && \
          cd singularity-ce-${SINGULARITY_VERSION} && \
          ./mconfig -p /usr/local && \
          make -C builddir && \
          sudo make -C builddir install

      - name: Build Container
        run: |
          sudo -E singularity build container.sif ${{ env.DEF_PATH }}

      - name: Archive built container
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: container
          path: container.sif

      - name: Login and deploy container
        if: github.event_name != 'pull_request' && ${{ !env.ACT }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${{ needs.generate-tag.outputs.tag }}

  # deploy-container:
  #   needs: [check-file-existence, generate-tag, build-container]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download a single artifact
  #       if: github.event_name != 'pull_request'
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: container
