name: Notify Maintainers
on:
  schedule:
    - cron: 0 12 1,15 * *

  # To test
  workflow_dispatch:

jobs:
  comment_on_issue:
    name: Comment on issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Open issue
        uses: actions-cool/issues-helper@v2
        with:
          actions: "open-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1

      - name: Create comment
        uses: actions-cool/issues-helper@v2
        with:
          actions: "create-comment"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 1
          body: |
            Please build the container and deploy it as a Github Package. It has been two weeks since the last reminder.
