name: Notify Maintainers
on:
  # schedule:
  #   - cron: 0 12 1,15 * *

  # To test
  workflow_dispatch:

jobs:
  notify-maintainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub CLI example
        run: gh issue list
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Notify maintainers
        run: |
          gh issue reopen 1
          gh issue comment 1 -F message.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
